# Lecture 1: Python & Numpy Tutorials

Ref:  http://cs231n.github.io/python-numpy-tutorial/


The Python programming language is a widely used tool for basic research and engineering. Its rapid rise in popularity is supported by comprehensive, largely open-source, contributions from scientists who use it for their own work.

There are currently two different supported versions of Python, 2.7 and 3.7, if you install using Anaconda (as of September 2019). Python 3.X introduced many backwards-incompatible changes to the language, so code written for 2.7 may not work under 3.7 and vice versa. 

Python itself is a programming language that stands on its own. It can be incorporated into other more complex, and potentially more useful interfaces. To solve problem with python, at a minimum you will need a text editor. With that you can read and write program files, and run them as a program either by having "python" read the file, or by making the file itself executable (as on Linux and Mac).

This tutorial is written in the format of an ipython-notebook to be used in a Jupyter environment. The widely-used Jupyter system has been under development for more than a decade and is mature. You can read about it and even preview its capabilities on the web.  Unlike a simple Python program, the notebooks created by Jupyter are truly bodies of work that include data and analysis. It can be very useful for data documentation and exchange, and/or for educational media, as in this course.

Ref: $Jupyter Notebook: An Introduction$  https://realpython.com/jupyter-notebook-introduction/


## Basic data types

Like most languages, Python has a number of basic types including $integers, floats, booleans$, and $lists, strings$. These data types behave in ways that are similar to other programming languages, such as R or MATLAB.
https://docs.python.org/3.7/library/stdtypes.html

Formally the principal built-in data types in Python are $numerics, sequences, mappings, classes$ and $exceptions$, which we will introduce later as we need them.



### Numbers, Variables and Basic Expressions : 
Variables are created when they are first assigned values. (dynamical typing, unlike static typing in C or C++)

Variables are replaced with their values when used in expressions. 

Variables must be assigned before they can be used in expressions. 

Integers and floats work as you would expect from other languages:

In [1]:
print('ok')
a=12.34*5.678
print(a)
23/7.8

ok
70.06652


2.948717948717949

In [ ]:
print(11+3, 2.4*3, 1/3, 14//3, 14//3.0)  #// take just the integer part
x = 3.2          # assignment
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"
x += 1  # x=x+1
print(x)  # Prints "4"
x *= 2    # x=x*2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

Python 3.X integers support unlimited size, i.e. Python 3.X’s integer type automatically provides extra precision for large numbers like 2**1000 when needed (in 2.X, a separate long integer type handles numbers too large for the normal integer type in similar ways).

In [ ]:
x=2 ** 1000
print(x, type(x))
len(str(2 ** 1000000))   #How many digits in a really BIG number?

 ### Built-in Numeric Tools 
 Python also provides both built-in functions and standard library modules for numeric processing. The pow and abs built-in functions, for instance, compute powers and absolute values, respectively. Here are some examples of the built-in math module (which contains most of the tools in the C language’s math library) 

In [ ]:
import math 
print(math.floor(2.5), math.floor(-2.5), math.trunc(2.5), math.trunc(-2.5))
print( math.pi, math.e, math.sqrt(144), math.sqrt(2), math.log(math.e))
print( pow(2, 4), 2 ** 4, 2.0 ** 4.0 )
print( pow(2, -0.2), 2 ** -0.2, 2.0 ** -0.2 )
import random 
print(random.gauss(-10,15))
random.randint(1, 80) 

### Booleans: 
Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"
a=5
b=9
print(a>b, a<b, a==b)

### Strings: 
Python has great support for strings:

In [ ]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw, hw*3)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"
print(str.capitalize('asdf'), str.upper('asdf'))


https://docs.python.org/3.5/library/stdtypes.html#string-methods

String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(9))      # Right-justify a string, padding with spaces; 
print(s.center(9))     # Center a string, padding with spaces; 
print(s.replace('l', '(xy)'))  #Replace all instances of 1substring with another
print('  world '.strip())  # Strip leading and trailing whitespace; 
print('   spacious   '.lstrip())
print('   spacious   '.rstrip())
print('1,2,3'.split(','))
print('1,2,,3,'.split(','))

In [ ]:
S = 'studentName=John_Doe'
print(len(S))
#Strings are ordered collections of characters, so we can access their
#components by position.
print(S[:], S[0], S[-2], S[1:6])     # Indexing from front or end
print(S[2:], S[:-1])           #Slicing: extract a section; 
print(S[1:len(S):4])          #Skipping items; S[i:j:k] from i to k (exclusive) every k characters
print(S[::-1], S[13:3:-1])            # Reversing items

# Containers (Data Structures)

Python stores data in several different ways, but the most popular methods are $lists$ and $dictionaries$.
The Python built-in data-containers are: lists, dictionaries, sets, and tuples.

## Lists
A list, denoted by [  ], is the Python equivalent of an array, but is resizeable and can contain elements of different types. Operating on the elements in a list can only be done through iterative loops, which is computationally inefficient in Python.

In [ ]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

In [ ]:
nums = list(range(5))   # range is a built-in function that creates a list of integers
print(nums)             # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])        # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])         # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])         # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])          # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])        # Slice indices can be negative; prints "[0, 1, 2, 3]"
print(nums[:-2])        # "[0, 1, 2]"
nums[2:4] = [8, 9]      # Assign a new sublist to a slice
print(nums)             # Prints "[0, 1, 8, 9, 4]"

### Loops/iterations: 
We can loop (iterate) over the elements of a string or list, which are called 'iterables'.

In [ ]:
s1='Mary'
for x in s1: print(x)
    
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

In [ ]:
#to access to the index of each element within the body of a loop, use the built-in enumerate function:
#https://docs.python.org/3/library/functions.html#enumerate
animals = ['cat', 'dog', 'monkey', 'horse']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

In [ ]:
nums = list(range(6))  #nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x**2)
print(squares)   # Prints [0, 1, 4, 9, 16]
for x in range(6):  print(x**2)
#for i in range(1,11,2): print(i)   #range(i,j,k) i=start, j=stop, k=step
#for i in range(-9,-1,2): print(i) 
for i in range(-4,-11,-2): print('*',i) 
for i in xrange(-1,-11,-2): print(i)  #in Python 3.x xrange does not exist anymore!? watch out!
for i in xrange(1,11,2): print(i)  #for most cases range & xrange are the same

### Generating a list by loop

In [ ]:
nums = [0, 1, 2, 3, 4]  # simpler code using a list comprehension:
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

In [ ]:
#nums = list(range(11))  # List comprehensions can also contain conditions
odd_squares = [x ** 2 for x in range(13) if x % 2 == 1]
print(odd_squares)  

### Combining lists

In [ ]:
L2=list(zip(['a', 'b', 'c'], [5, 2, 3])) #Zip together 2 lists to form new list
print L2
for x, y in zip(['Alice', 'Betty', 'Charlie'], [15, 22, 17]):
    print x, y       #loop over a zipped-list

### Dictionaries
A dictionary, denoted by {   }, stores (key, value) pairs.

In [ ]:
d = {'cat': 'cute', 'dog': 'furry','boy':'fat'}  # Create a new dictionary
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('caty' in d)     # Check if a dictionary has a given key; prints "True"
print(d.keys()) 
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"
print(d)

In [ ]:
d0 = {'cat': 'animal', 'apple': 'fruit', 'snake': 'reptile', \
      'rose': 'flower'}
print(d0)

In [ ]:
d = {'adult': 2, 'old man': 3, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('%s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

In [ ]:
nums = list(range(11))  # [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

### Sets
A set, {  }, is an unordered collection of unique/distinct and immutable objects (elements) that supports operations corresponding to mathematical set theory.  By definition, an item appears only once in a set, no matter how many times it is added. 

In [ ]:
x = set('abcdea') 
y = set('bcdxyyz') 
print(x,y, x-y, y-x)  #difference
print(x|y, x&y)     #union, intersection
print(x^y)     #Symmetric difference (XOR) 
print(x > y, x < y)          # Superset, subset 
print('e' in x, 'e' in y)    # Membership 
#defined to work on all other collection types
print('e' in 'europe',  22 in [11, 22, 33] ) 


In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

In [ ]:
from math import sqrt   
nums = {int(sqrt(x)) for x in range(90)}  #set comprehensions
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

### Tuples
A tuple is an (immutable) ordered list of values whose size and contents cannot be modified. A tuple is in many ways similar to a list; one of the most important differences is that tuples are of fixed length and can be used as keys in dictionaries and as elements of sets, while lists cannot.

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

### Control statements (if, elif,  else) and Ternary expressions 
The if statement controls the flow of program action.

A ternary expression in Python allows you to combine an if-else block that produces a value into a single line or expression. The syntax for this in Python is:
$value=[true-expr]$ if  $[condition]$ else $[false-expr]$

It has the identical effect as the more verbose:

if condition:    

\ \ value = true-expr 
  
else:   

\ \ value = false-expr 

In [ ]:
x=7
if x < 0:    print("It's negative") 
if x < 0:    
    print("It's negative") 
elif x == 0:
    print('Equal to zero') 
elif 0 < x < 5:    
    print('Positive but smaller than 5') 
else:    
    print('Positive and larger than or equal to 5') 
    
print( 'Non-negative' if x >= 0 else 'Negative' )                   

## Functions
https://docs.python.org/3.5/tutorial/controlflow.html#defining-functions

Python functions are defined using the def keyword

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

In [ ]:
def fib(n):    
     """Print a Fibonacci series up to n"""
     a, b = 1, 2
     while a < n:   #while loop
         print(a)  #print(a, end=' ')
         a, b = b, a+b
     print('end')
# Now call the function we just defined:
fib(2000)

In [ ]:
def fibon(n):    # write all Fibonacci numbers up to n
     # Return a Fibonacci series up to n.
     a, b = 2, 3
     fib = [a, b]
     while a < n:
        a, b = b, a+b
        fib.append(b)
     return fib
# Now call the function we just defined:
print(fibon(200000))

In [ ]:
import sys, time
def factor3(n):  # find all factors of n
  d = 2
  factors = [ ]
  while n % d == 0:
    factors.append(d)
    n = n/d
  d = 3
  while n > 1 and d*d <= n:
    if n % d == 0:
      factors.append(d)
      n = n/d
    else:
      d = d + 2
  if n > 1: 
    factors.append(n)
  return factors
t1 = time.time()
xx=2**51 + 1
xf=factor3(xx)
print(len(xf), xf)
xp=1
for x in xf:
    xp=xp*x
print(xx, xp)

dict={2:[2], 3:[3]}
fib=fibon(xx)
print(fib)
for x in fib:
  xf=factor3(x)
  dict[x]=xf
  print(x, len(xf), xf)
#print(dict)
t2 = time.time()
print("time: ", t2 - t1)

#### Assignment:
1.1 When using 'print(dict)', the result of the printing a dictionary is not in order. 
Try write a code to print 'dict' in ascending or descending order of the key, using  d0 = {'cat': 'animal', 'apple': 'fruit', 'snake': 'reptile', 'rose': 'flower'} as an example. 
Hint: use the python function sorted() on keys().

1.2 Write a function to count the number of all Fibonacci numbers less then N.

1.3 Write a function to count the number of all prime numbers less then N.

1.4 If N is a positive integer, the total number of positive integers that are relatively prime to N and less than N is denoted by $\phi(N)$. It is  called the Euler function of $N$. For example, we have $\phi(2)=1$, $\phi(3)=\phi(4)=2$, and if $p$ is a prime number then $\phi(p)=p-1$.
Write a python function to calculate $\phi(N)$.

1.5 A positive integer is called a perfect number if by adding all the positive divisors of the number (except itself), the result is the number itself. The first perfect number is 6 [=1+2+3]. Other perfect numbers include 28 [=1+2+7+4+14], 496 and 8128. Write a python function to calculate all perfect numbers less than or equal to N.

In [ ]:
mydict = {'carl':40,
          'alan':2,
          'bob':1,
          'danny':3} 
for key in sorted(mydict.keys()):
    print("%s: %s" % (key, mydict[key])) 


## Classes
If you do not have any previous experience with object-oriented (OO) programming, you may want to consult an introductory course or a tutorial on it so that you have a grasp of the basic concepts.

Here is a very brief introduction of Object-Oriented Programming (OOP) to bring you to speed −

    Class − A user-defined prototype for an object that defines a set of attributes that characterize any object of the class. The attributes are data members (class variables and instance variables) and methods, accessed via dot notation.

    Class variable − A variable that is shared by all instances of a class. Class variables are defined within a class but outside any of the class's methods. Class variables are not used as frequently as instance variables are.

    Data member − A class variable or instance variable that holds data associated with a class and its objects.

    Function overloading − The assignment of more than one behavior to a particular function. The operation performed varies by the types of objects or arguments involved.

    Instance variable − A variable that is defined inside a method and belongs only to the current instance of a class.

    Inheritance − The transfer of the characteristics of a class to other classes that are derived from it.

    Instance − An individual object of a certain class. An object obj that belongs to a class Circle, for example, is an instance of the class Circle.

    Instantiation − The creation of an instance of a class.

    Method − A special kind of function that is defined in a class definition.

    Object − A unique instance of a data structure that's defined by its class. An object comprises both data members (class variables and instance variables) and methods.

    Operator overloading − The assignment of more than one function to a particular operator.

https://www.tutorialspoint.com/python/python_classes_objects.htm


Simply speaking, objects are an encapsulation of variables and functions into a single entity. Objects get their variables and functions from classes. Classes are essentially a template to create your objects.

Python has been an object-oriented language since it existed. Because of this, creating and using classes and objects are easy. The syntax for defining classes in Python is straightforward:

In [ ]:
class Greeter(object):
    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HI, %s! Good Morning' % self.name.upper())
        else:
            print('Hello, %s, how are you' % self.name)

g = Greeter('Maria')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

In [ ]:
class friend(object):
    #common variable for the class 'friend' shared by all instances
    fCount = 0
    #Constructor
    def __init__(self, name, phone=0):
        self.name = name  # Create an instance variable
        if phone != 0:
            self.phone = phone
        else:
            self.phone = 0
        friend.fCount += 1  #fCount increases by 1 for each creation
   
    def displayCount(self):
        print("Total friends: %d" % friend.fCount)

    # Instance methods
    def greet(self, loud=False):
        if loud:
            print('HI, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)
    def callc(self):
        print("HI, %s's phone number is %d" % (self.name.upper(), self.phone))

f1 = friend('Maria', 223344)  # Construct an instance of the class
f1.greet()   
f1.displayCount() 
f2 = friend('John')

f3 = friend('Zhang San', 11223345)
         
f1.callc() 
f2.greet()  
f2.callc()
f3.greet(True)  
f3.displayCount()

#### Assignment 1.6
Write a $Student$ class to hold all information of a UIC student, which includes name, gender, birthday, major, the year began study in UIC,  a list of courses already taken, and a list of courses taking currently. Aslo provide the following functions in this $Student$ class:

[1] add a course to the list of courses taking currently.

[2] drop a course from the list of courses taking currently.

[3] print the list of courses taking currently and the total number.

[4] print the list of courses already taken and the total number.

Write a simple python program to construct a $Student$ object with the name ='Mary Li' and all required information about her, then exercise/call the four functions above to show how they work.

# Numpy
NumPy is the fundamental Python package for scientific computing. It adds the capabilities of N-dimensional arrays, element-by-element operations (broadcasting), core mathematical operations like linear algebra, and the ability to wrap C/C++/Fortran code.

One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data. There are a number of reasons for this: 

• NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s library of algorithms written in the C language can operate on this memory without any type checking or other overhead. NumPy arrays also use much less memory than built-in Python sequences. 

• NumPy operations perform complex computations on entire arrays without the need for Python for loops.


## Arrays
A Python $list$ object can store nearly any type of Python object as an element. However, a numpy $array$ is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the $\bf{rank}$ of the array; the $\bf{shape}$ of an array is a tuple of integers giving the size of the array along each dimension.
With NumPy arrays, you can only store the same type of element, e.g., all elements must be floats, integers, or strings. However, when it comes to operation times,  the NumPy $array$ operations are sped up significantly over that of Python $list$, because operation on the elements in a $list$ can only be done through iterative loops, which is computationally inefficient in Python.

NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory. 

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000)) 
# to test the speed of np array operation
# from chapter4 of "Python for Data Analysis Data Wrangling with Pandas, 
# NumPy, and IPython" by Wes McKinney 
%time for _ in range(10): my_arr2 = my_arr * 2 
%time for _ in range(10): my_list2 = [x * 2 for x in my_list] 

In [ ]:
import numpy as np
alist = [1, 2, 3]
a = np.array(alist)       # Create a rank 1 array from a list
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape, a.ndim)            # Prints "(3,) 1"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print('array:',a, ' list:',a.tolist())                  # Prints "[5, 2, 3]"

arr1 = np.array([1, 2, 3], dtype=np.float64)

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape, b.ndim)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

a = np.arange(9)
print('a=',a, a.shape)

a = np.zeros((2,2))   # Create an array of all zeros
b = np.ones((1,2))    # Create an array of all ones
print(a, b)              # Prints "[[ 1.  1.]]"
c = np.full((2,2), 7)  # Create a constant array
d = np.eye(2)         # Create a 2x2 identity matrix
print(c, d)           # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
a = np.array(range(10), float) 
print(a)
a1 = a.reshape((5, 2))  #reshape a array to a different matrix, it creates a new array
a2 = a.reshape((2, 5))  # and does not modify the original array.    
print('a1=',a1, 'a2=',a2)
a1[0,0]=12.  #a & a1 are just references/pointers, when we change a1[0,0], a[0,0] also changed
print('a=',a,'a1=',a1)

### Array indexing
Numpy offers several ways to index into arrays.

#### Slicing: 
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]   # rows from 0 to 1; columns from 1 to 2
print(b)
print(a[0, 1])   # Prints "2"
b[0, 0] = 13     # b[0, 0]  same data as a[0, 1], implemented by pointer
print(a[0, 1])   # Prints "13"
print(np.reshape(a,(4,3)))  #reshape not changing a
a = np.reshape(a,(4,3))    #reshape changing a
"""You can also mix integer indexing with slice indexing. However, 
doing so will yield an array of lower rank than the original array. 
Note that this is quite different from the way that MATLAB 
handles array slicing:"""
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[0, :]    # Rank 1 view of the first row of a
row_r2 = a[0:1, :]  # Rank 2 view of the first row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

#### Integer array indexing: 
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

#### Boolean array indexing: 
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. 
More details about numpy array indexing can be found in the documentation: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html 

Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

###  Conditional Logic as Array Operations 

In [ ]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False]) 
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result, type(result))
result1 = np.where(cond, xarr, yarr)
print(result1, type(result1)) 

arr = np.random.randn(4, 4)
print(arr,'\n', arr>0)
ar1=np.where(arr<0, 0, arr) # set negative values to 0 
print(ar1)

### Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.
https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

Here is an example:

In [ ]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

### Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print('x+y', x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print('x-y', x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print('x*y', x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print('x/y', x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print('sqrt', np.sqrt(x))


Unlike MATLAB, '*' is elementwise multiplication in NumPy, not matrix multiplication. The dot function is used to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. $'dot'$ is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print('v.dot(w)', v.dot(w))
print('dot(v,w)', np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print('x.dot(v)', x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print('x.dot(y)', x.dot(y))
print(np.dot(x, y))
print('y.dot(x)', y.dot(x))  #different from x.dot(y)
print(np.dot(y, x))

In [ ]:
import numpy as np
x = np.array([[1,2],[3,4]])
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

# https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [ ]:
import numpy as np  # to transpose a matrix
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

### Broadcasting
NumPy specializes in numerical processing through multi-dimensional ndarrays,
where the arrays allow element-by-element operations, a.k.a. broadcasting.

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
import numpy as np
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

However when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [ ]:
import numpy as np
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv, vv.shape)       # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
print(x.shape, v.shape, np.array([[1, 0, 1]]).shape) 

The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible in all dimensions.
After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
If this explanation does not make sense, try reading the explanation from the documentation or this explanation.

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation.

Here are some applications of broadcasting:

In [ ]:
import numpy as np
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print('1:', np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print('2:', x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) [[1,2,3], [4,5,6]]；and w shape (2,). 【4，5】
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print('3:', (x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print('4:', x + np.reshape(w, (2, 1)))
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print('5:', x * 2)

In [ ]:
x1 = np.array([[1,2,3], [4,5,6],[7,8,9]])
w1 = np.array([1,0,1])
print(x1+w1,'\n6:',x1+np.reshape(w1,(3,1)),'\n7:',x1+np.reshape(w1,(3,)))
print('8:',x1*np.reshape(w1,(3,1)),'\n9:',x1*np.reshape(w1,(3,)))

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

### Numpy Documentation
This brief overview has touched on many of the important things that you 
need to know about numpy, but is far from complete. Check out the numpy 
reference to find out much more about numpy.

https://docs.scipy.org/doc/numpy/reference/

For example:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html


In [ ]:
import numpy as np 
print(np.random.randn())
arr = np.random.randn(4, 4)
ar1=np.where(arr<0, 0, arr) # set negative values to 0 
print(ar1)
print(np.eye(4, k=1, dtype=float))
print(np.eye(4, k=0, dtype=float))
np.identity(4, dtype=float) 

## Array iteration 
It is possible to iterate over arrays in a manner similar to that of lists: 

In [ ]:
import numpy as np 
a = np.array([1, 4, 5])
for x in a:
    print(x)
a = np.array([[1, 2], [3, 4], [5, 6]])
for x in a:
    print(x)
for x,y in a:
    print(x*y)

## Basic array operations 
Many functions exist for extracting whole-array properties.  The items in an array can be summed or multiplied: 

In [ ]:
import numpy as np 
a = np.array([2, 4, 3.8, 5, 1.1]) 
print(a.sum(), np.sum(a))
print(a.prod(), np.prod(a))
print(sorted(a))
print('2:',a.mean(), a.var(), a.std(), a.min(), a.max(), \
     '\n3:', a.argmin(), a.argmax(), np.median(a))

arr = np.random.randn(2, 4)
print(arr)
print(np.mean(arr))  
print(np.mean(arr,axis=0)) 
print(np.mean(arr,axis=1)) 
print(np.std(arr))  
print(np.std(arr,axis=0)) 
print(np.std(arr,axis=1)) 
print(np.var(arr))  
print('var:',np.var(arr,axis=0),'\nvar:',np.var(arr,axis=1)) 


a = np.array([1, 3, 0, 2.3], float)
b = np.array([0, 3, 2, -1.4], float)
print(a > b, a==b, a<b, a<=b, a>2) 
print(np.logical_and(a > 0, a < 3))
print(np.logical_or(a > 0, a < 3))
print(np.logical_not(a > 0))
print('where:',np.where(a>1), np.where(b<0))

In [ ]:
import numpy as np 
s1=np.array(['boy','ape','dog','cat','big','den'])
print(sorted(s1),s1.shape)
print(sorted(s1, reverse=True))
# Order parameter in sort function 
dt = np.dtype([('name', 'S4'),('age', int)]) 
a = np.array([("ravi",21),("anne",25),("mo", 17), ("eve",27)], dtype = dt) 
print('Order by name:',np.sort(a, order = 'name'))
print('Order by age:',np.sort(a, order = 'age'))
dt = np.dtype([('name', 'S4'),('grade', 'S1')])
s2=np.array([('bety','a'),('alan','c'),('dana','d'),\
             ('cali','e'),('eve','b')],dtype = dt) 
print(s2)
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.sort.html?highlight=sort#numpy.ndarray.sort
#https://www.tutorialspoint.com/numpy/numpy_sort_search_counting_functions.htm
print('Order by name:',np.sort(s2, order = 'name'))
print('Order by grade:',np.sort(s2, order = 'grade'))
a1=np.random.randint(33, size=12)
print(a1)
a2=np.reshape(a1,(4,3) )
print(a2)
a2.sort()  #axis=-1; Default is -1, which means sort along the last axis.
# sort each row independently
print(a2)
a2.sort(axis=0) 
print(a2)

#### Assignment
1.1 When using 'print(dict)', the result of the printing is not in order. 
Try write a code to print 'dict' in ascending or descending order of the key, using  d0 = {'cat': 'animal', 'apple': 'fruit', 'snake': 'reptile', 'rose': 'flower'} as an example. 

1.7 Write a Python code to create a Numpy array of the shape (7,4) [7 rows & 4 columns] so that each column is a sample of random numbers with normal distributions N(0,1), N(1,3), N(-1,4), N(-2,6), where N(a,b) is a normal distribution with mean=a and variance=b. 

1.8 Create a Numpy array of random numbers by: arr = np.random.randn(4, 5). Write a few lines of python code to sort the columns of the array in ascending order according to the the first row, so that all 5 columns remain unchanged except their relative positions.
Run your program to confirm it produces the desired result.

1.9 Repeat the last problem so that instead of sorting the columns we sort the rows this time. The result is a matrix with all 4 rows unchanged except their relative positions with respect to each other.
Run your program to confirm it produces the desired result.


# SciPy
SciPy is built on the NumPy array framework and takes scientific programming to
a whole new level by supplying advanced mathematical functions like integration,
ordinary differential equation solvers, special functions, optimizations, and more.

Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays. SciPy builds on this, and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications. You can look them up here:
https://docs.scipy.org/doc/scipy/reference/index.html. 

We will highlight some parts of SciPy that you might find useful for this class.


### Image operations
SciPy provides some basic functions to work with images. For example, it has functions to read images from disk into numpy arrays, to write numpy arrays to disk as images, and to resize images. Here is a simple example that showcases these functions:

In [ ]:
from scipy.misc import imread, imsave, imresize
# Read an JPEG image into a numpy array
img = imread('neuralnethuman.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (152L, 330L, 3L)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (152L, 330L, 3L);
# we multiply it by the array [1, 0.9, 0.7] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.2]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (200, 300))

# Write the tinted image back to disk
imsave('nnh_tinted.jpg', img_tinted)
print(img_tinted.dtype, img_tinted.shape)

# Matplotlib
Matplotlib is a Python 2D plotting library which produces publication quality figures. For simple plotting the $matplotlib.pyplot$ module provides a MATLAB-like interface. For the power user, you have full control of line styles, font properties, axes properties, etc, via an object oriented interface or via a set of functions familiar to MATLAB users.

https://matplotlib.org/

https://matplotlib.org/resources/index.html


### Plotting
The most important function in matplotlib is plot, which allows you to plot 2D data. Here is a quick and dirty example:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()  # You must call plt.show() to make graphics appear.

In [ ]:
# Plot multiple lines at once, and add title, legend, and axis labels:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

In [ ]:
# Plot different things in the same figure using the subplot function. 
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

In [ ]:
# Use the imshow function to show images. Here is an example:
import numpy as np
from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

img = imread('neuralnethuman.jpg')
img_tinted = img * [1, 0.95, 0.1]

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(img_tinted))
plt.show()

#### Assignment: Poincaré plot
Given a time series of the form
$x_t$, $x_{t+1}$, $x_{t+2}$, $x_{t+3}$, ...

a Poincaré plot  first plots ($x_t$, $x_{t+1}$), then plots ($x_{t+1}$, $x_{t+2}$), then ($x_{t+2}$, $x_{t+3}$), and so on. 

1.10 Use the scatter-plot in matplotlib.pyplot to plot the Poincaré plot of the Fibonacci series less then $2^{200}$, both in linear scale and in log scale. [Assignment 1.2]

1.11 Similarly, produce the Poincaré plot of the series of the log of prime numbers less then $2^{20}$. [Assignment 1.3]

1.12 Similarly, produce the Poincaré plot of the series of the log of perfect numbers less then $2^{20}$. [Assignment 1.5]

### Quiz
[A] Write a Python function to return a list of prime numbers less than N, where N is an integer larger than 3, by the following algorithm:

a/ initialize a list of primes, ps = [2, 3], by inserting the first 2 prime numbers in it;

b/ initiate a loop with its counter, x, running from 4 to an integer just less than N, with step_size=1.
For each x in this loop, check the following:
if x is divisible by any member of ps, then x is not a prime number and we proceed to the next x;
if x is not divisible by all members of ps, then x is a prime and we add x into the list ps.

c/ return ps at the end of the function.

Test your function with N=2000.

Find out the the computer time used by this function call, by calling the time.time() function.

Explain why this algorithm works. 

Try another algorithm of your choice to get the same answer, i.e. to produce the list of prime numbers less than N, using a different algorithm that you are familiar with, for example: the "Sieve of Eratosthenes". Compare the answers from these 2 algorithms to make sure they give the same answer. 
Compare the the computer time used by this function call, with the first one.
Explain why one of them is faster than the other.



[B] Use the function from the previous problem to generate a sequence of prime numbers less than N=10**5. Use it to calculate the sequence of first difference of successive prime numbers, $\delta p_i$ = $p_i$ - $p_{i-1}$, where $p_i$ are the $i$th prime number.

Write Python program that will produce 
(a) histrogram, and
(b) Poincaré plot 

for the sequence of $\delta p_i$.

For you information, given a series of the form
$x_t$, $x_{t+1}$, $x_{t+2}$, $x_{t+3}$, ...

a Poincaré plot is a scatter plot that first plots ($x_t$, $x_{t+1}$), then plots ($x_{t+1}$, $x_{t+2}$), then ($x_{t+2}$, $x_{t+3}$), and so on, to the last pair. 





In [ ]:
def primelessthan(n):  #return list of prime numbers less than n, for n>3
    primes=[2,3]
    for x in range(4,n):
        isprime=True
        for i in primes:
            if x%i == 0: 
                isprime=False
                break
            else: continue
        if isprime: 
            primes.append(x) 
    return primes
import time
t1=time.time() 
N=10**6
a1=primelessthan(N) 
print('number of primes less than %d is %d', N,len(a1))
t2=time.time() 
print('time used:',t2-t1)
                
import numpy as np
import matplotlib.pyplot as plt
xa=np.array(a1[0:-1])
ya=np.array(a1[1:])
pd=ya-xa
xa=pd[0:-1]
ya=pd[1:]
print(len(xa),len(ya))
print(xa[0:9],'\n',ya[0:9])
plt.scatter(xa,ya) 
plt.show()
plt.hist(pd, bins='auto') 
plt.show() 

In [ ]:
def primelessthan(n):  #return list of prime numbers less than n, for n>3
    primes=[2,3]
    for x in range(4,n):
        isprime=True
        for i in primes:
            if i*i>x: break
            if x%i == 0: 
                isprime=False
                break
            else: continue
        if isprime: 
            primes.append(x) 
    return primes, len(primes)
import time
t1=time.time() 
print(primelessthan(2000))
t2=time.time() 
print('time used:',t2-t1)


A prime number that is one less than a power of two is known as a Mersenne prime, i.e. a prime number of the form $M_n = 2^n − 1$ for some integer n. They are named after Marin Mersenne, a French Catholic Church friar, who studied them in the early 17th century.
Write a python program to find the first 7 Mersenne primes (3, 7, 31, 127, 8191, 131071, 524287).

According to the Euclid–Euler theorem in number theory, every even perfect number has the form $2^{n − 1}(2^n − 1)$, where $2^n − 1$ is a Mersenne prime. Create a list of the first 7 perfect numbers and verify that the Euclid–Euler theorem is indeed valid.





In [ ]:
import numpy as np   #final exam
a0 = np.array([1, 2, 3])
print(a0.shape)
a1 = np.array([[1], [2], [3]])
print(a0.shape)
a2 = np.reshape(np.array(range(12)), (3,4))
print(a2)
a3 = [0, 0.1, 0.2, 0.3]
print(a2+a3) #5 marks
print(np.sum(a2, axis=1))

for x in "pythongood":
    if x == "o": break
    print(x)
print("The end1")
for x in "pythongood":
    if x == "o": continue
    print(x)
print("The end2")

numList = [1, 2, 3, 4, 5]
strList = ['one', 'two', 'three']
for x, y in zip(numList, strList):
    print(x,y)

In [ ]:
import numpy as np
class NeuralNetwork:
  def __init__(self, numInput, numHidden, numOutput):
    self.ni = numInput
    self.nh = numHidden
    self.no = numOutput
    self.iNodes = np.zeros(shape=self.ni, dtype=np.float64)
    self.hNodes = np.zeros(shape=self.nh, dtype=np.float64)
    self.oNodes = np.zeros(shape=self.no, dtype=np.float64)
    self.ihWeights = np.random.randn(self.ni, self.nh)
    self.hoWeights = np.random.randn(self.nh, self.no)
    self.hBiases = np.random.randn(self.nh)
    self.oBiases = np.random.randn(self.no)
    print(self.iNodes, '\n', self.ihWeights)
    print(self.oNodes, '\n', self.hoWeights)
ann1= NeuralNetwork(4,3,2)

In [ ]:
['alan', 21, 'a'], ['ramy', 19, 'd'], ['mary',17, 'b'], ['cali', 20,'e'], ['dana',22,'c']

[C] Write a Python function, F(N), to find and count all $(x, y)$ pairs such that (i) x, y are positive integers and both x & y are less than N, a given positve integer, and they cannot be equal to 0; (ii) $x^2 + y^2 = c^2$, where c is any positive integer less than or equal to N.
For example, (3,4) and (4,3) are considered as one and the same pair counted in the whole set with c=5.

Use the function you develop to calculate F(10) & F(100).

In [ ]:
def pyF(N):
    n2=[c**2 for c in range(1,N)]
    pairs=[]
    for x in range(1,N):
        for y in range(1,x+1):
            if x**2 + y**2 in n2: pairs.append(set([x,y]))
    return pairs
py=pyF(250)
print(len(py),  py, type(py))   
py1=set(tuple(r) for r in py)
print(py1, len(py1))

In [ ]:
def pyF(N):
    n2=[c**3 for c in range(1,N)]
    pairs=[]
    for x in range(1,N):
        for y in range(1,N):
            for z in range(1,N):
                if x**2 + y**2 + z**2 in n2: pairs.append([x,y,z]) 
    return pairs
py=pyF(40)
print(len(py),  py) 
py1=set(tuple(r) for r in py)
print('\n**',len(py1), py1)

[E] Calculate the product of the following two matrices by using the correct Numpy function:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[1, -2], [-3, 4], [5, -6]] 

In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, -2], [-3, 4], [5, -6]])
c = A.dot(B)
print(c)