# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for woking with these arrays. 

## Array 
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python liests, and access elements using square brackets:

In [2]:
import numpy as np

a  = np.array([1,2,3]) # Create a rank 1 array 
print(type(a)) 
print(a.shape)
print(a[0],a[1],a[2])
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[1 2 3]
(2, 3)
1 2 4


Numpy also provides many function to create arrays:
*You can get more information from the <a href="https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation"> official doc.</a>

In [3]:
a = np.zeros((2,2)) # an array of all zeros
print('a is', a) 

b = np.ones((1,2)) # crate an array of all ones
print('b is', b)

c = np.full((2,2,),7) # crate an array of one constant 
print('c is', c)

d = np.eye(2) # a 2 times 2 identity matrix
print('d is', d)

e = np.random.random((2,2)) # an array with random values
print('e is',e)

a is [[0. 0.]
 [0. 0.]]
b is [[1. 1.]]
c is [[7 7]
 [7 7]]
d is [[1. 0.]
 [0. 1.]]
e is [[0.48302711 0.32431927]
 [0.69838647 0.3540748 ]]


## Array indexing

Numpy offers serval ways to index into arrays.
**Slicing**: Since Array could be a high-dimensional, we must specify a slice for each dimension of the array.

In [4]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print("\n")
b = a[1:3,1:2]
print(b)
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print("\n")
print(a[1,2]) # before the comma it represents the row; the after one is the column

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 6]
 [10]]


7


## Datatypes

Every numpy array is a fride of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional arguments to explicity specify the datatype. Here is an example: 

In [5]:
# Let numpy choose the datatype
x_int64 = np.array([1,2])
print(x_int64.dtype) #Prints "int64"

x_float64 = np.array([1.0,2.0])
print(x_float64.dtype) # Prints "float64"

x_1 = np.array([1,2], dtype = np.float64)
print(x_1.dtype)

int64
float64
float64


## Array Math 

We can use array to do the math work, but we can also think about this is matrix's work. Actually, the numpy provide us a way to us matrix.
Returns a matrix from an array-like object, or from a string of data $\dots$ A matrix is a specialized 2-D array that retains its 2-D natrue through operations. 
**we can replace the `matrix` command by using `array` and the doc. also ask us to replace it**.

Actually, in `numpy` we can do a lot of thing with the `array`.

In [6]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)

# Additon
print("The answer of 'x + y' is", "\n", x + y)
print("The answer of 'x + y' is", "\n", np.add(x,y))

# Sbutraction 
print("The answer of 'x - y' is", "\n", x - y)
print("The answer of 'x - y' is", "\n", np.subtract(x, y))

# Multiplication 

print("The answer of 'x * y' is", "\n", x * y)
print("The answer of 'x * y' is", "\n", np.multiply(x, y))

# Division
print("The answer of 'x * y' is", "\n", x / y)
print("The answer of 'x * y' is", "\n", np.divide(x, y))

# Square Root
print("The answer of square root of x is", "\n", np.sqrt(x))

The answer of 'x + y' is 
 [[ 6.  8.]
 [10. 12.]]
The answer of 'x + y' is 
 [[ 6.  8.]
 [10. 12.]]
The answer of 'x - y' is 
 [[-4. -4.]
 [-4. -4.]]
The answer of 'x - y' is 
 [[-4. -4.]
 [-4. -4.]]
The answer of 'x * y' is 
 [[ 5. 12.]
 [21. 32.]]
The answer of 'x * y' is 
 [[ 5. 12.]
 [21. 32.]]
The answer of 'x * y' is 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
The answer of 'x * y' is 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
The answer of square root of x is 
 [[1.         1.41421356]
 [1.73205081 2.        ]]


For the further infromation check: <a href="http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html"> Official Doc.</a>